os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build test -project Breathe.xcodeproj -scheme Breathe -destination "platform=iOS Simulator,name=iPhone 8, OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
